#!/usr/bin/env php
<?php

/**
 * Load correct autoloader depending on install location.
 */
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else {
    require __DIR__ . '/../../autoload.php';
}

use Mpociot\Documentarian\Documentarian;
use Silly\Application;

$documentarian = new Documentarian();

$app = new Application('Documentarian', 'v0.1.0');

$app->command('generate [source] [destination]', function ($source, $destination) use ($documentarian) {
    $documentarian->generate($source, $destination);
    info("Generated documentation from $source to $destination.");
});

$app->run();