#!/usr/bin/env php
<?php

/**
 * Load correct autoloader depending on install location.
 */
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else {
    require __DIR__ . '/../../autoload.php';
}

use Shalvah\Pastel\Pastel;
use Silly\Application;

$pastel = new Pastel();

$app = new Application('Pastel', 'v0.1.0');

$app->command('generate [source] [destination]', function ($source, $destination) use ($pastel) {
    $pastel->generate($source, $destination);
    info("Generated documentation from $source to $destination.");
});

$app->run();